"""added added_by field

Revision ID: 19e1791bea8c
Revises: 
Create Date: 2024-02-09 12:57:30.516824

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '19e1791bea8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinion', sa.Column('added_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opinion', 'added_by')
    # ### end Alembic commands ###
